import React from 'react';
import Head from "next/head";
import { useRouter } from 'next/router'
import Link from 'next/link';
import { Layout, Menu, BackTop } from "antd";
import { UpOutlined } from '@ant-design/icons';
const { Header, Sider } = Layout;

import HeaderComponent from './Header/Header';
import FooterComponent from './Footer/Footer';
import HeaderLogin from './HeaderLogin';

import style from './layout.module.scss'
import nav from './data/data.js'

function LayoutComponent({ children }) {
    const router = useRouter()
    const path = router.pathname

    const items2 = nav.map((item) => {
        return {
            key: item.id,
            label: <Link href={`/category/${item.id}`}>{item.title}</Link>,
        };
    });




    return (
        <>
            <Head>
                <title>Onea.</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                path !== '/login' ?
                    <Layout>
                        <Header className={style.header}>
                            <HeaderComponent />
                        </Header>
                        <Layout className={style["max-width"]}>
                            {path !== "/cart" ?
                                <Sider>
                                    <Menu
                                        mode="inline"
                                        selectedKeys={[path === '/' ? '0' : router.query.category]}
                                        style={{
                                            height: '100%',
                                        }}
                                        items={items2}
                                    />
                                </Sider>
                                : null
                            }
                            {children}
                        </Layout>
                        <FooterComponent />
                        <BackTop>
                            <div className={style["up"]}><UpOutlined /></div>
                        </BackTop>
                    </Layout > :
                    <Layout style={{ height: '100vh' }}>
                        <Header className={style.header}>
                            <HeaderLogin />
                        </Header>
                        {children}
                        <FooterComponent />
                    </Layout>
            }
        </>
    );
}

export default LayoutComponent;